<Project>
  <Target Name="GenerateFormeApplicationManifest" BeforeTargets="PrepareForBuild" Condition="'$(MSBuildProjectName)' == 'Forme.App' Or '$(MSBuildProjectName)' == 'Forme.Setup'">
    <ReadLinesFromFile File="$(MSBuildThisFileDirectory)src/Forme.App/app.manifest">
      <Output TaskParameter="Lines" ItemName="_formeManifestLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <_formeManifestContent>@(_formeManifestLines, '%0A')</_formeManifestContent>
      <_formeGeneratedManifest>$(IntermediateOutputPath)Forme.app.manifest</_formeGeneratedManifest>
      <ApplicationManifest>$(_formeGeneratedManifest)</ApplicationManifest>
    </PropertyGroup>
    <WriteLinesToFile File="$(_formeGeneratedManifest)" Lines="$([System.String]::Copy('$(_formeManifestContent)').Replace('__FORME_VERSION__', '$(FormeVersion).0'))" Overwrite="true" />
  </Target>
</Project>
