<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><RuntimeIdentifiers>win-x64</RuntimeIdentifiers></PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Content/*.json" LogicalName="Forme.Core.%(Filename)%(Extension)" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>
</Project>
